### ISSUE TITLE
Websockets do not work properly.

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/discord-bot#6]
Due to issues with firewalls or something, when opening a websocket to a `wss://_____` address, the thing seems to instead convert it to a `https://____` request, which the apache proxy does not forward properly.

Suggested change:

Have a `/wss` subdomain, so the websocket makes a request to `wss://ml-api.uk.ms/wss/....`, which even if the request fails and goes to `https://ml-api.uk.ms/wss`, we can proxy properly.

**Comment by anushan001** [comment]
shush

**Comment by CheAle14** [comment]
This issue has been solved by whitelist to firewall.  
Apache frontend should attempt to proxy any websocket connections with `Sec-WebSocket-Key` even if it does not contain the Connection: upgrade headers.
